### ISSUE TITLE
Jasmine issue.

### ISSUE THREAD

**Issue by codestorycooked** [bjornicus/tddcss#2]
Hi ,
I am having issue with jasmine. Could you please help. 

karma.config.js : 
//uncommented this line
frameworks: ['jasmine', 'commonjs'],

on Cosole ran this  command :

C:\project directory>karma start

ERROR Output: 

D:\Samples\tddcss>karma start
WARN [karma]: Port 9876 in use
INFO [karma]: Karma v0.12.31 server started at http://localhost:9877/
INFO [launcher]: Starting browser Chrome
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Windows 7)]: Connected on socket uiOlTJAM-QU5vLv2986q with id 17995088
INFO [Chrome 42.0.2311 (Windows 7)]: Connected on socket my7g_mkXdHfNkBSn986r with id 1411949
PhantomJS 1.9.8 (Windows 7) Testing Kendo UI test encountered a declaration exception FAILED
        ReferenceError: Can't find variable: before
            at D:/Samples/tddcss/js/kendoUItest.js:19
            at D:/Samples/tddcss/js/kendoUItest.js:59
            at runModule (D:/Samples/tddcss/node_modules/karma-commonjs/client/commonjs_bridge.js:40)
            at require (D:/Samples/tddcss/node_modules/karma-commonjs/client/commonjs_bridge.js:79)
            at D:/Samples/tddcss/node_modules/karma-commonjs/client/commonjs_bridge.js:141
            at D:/Samples/tddcss/node_modules/karma-commonjs/client/commonjs_bridge.js:145
PhantomJS 1.9.8 (Windows 7) My page encountered a declaration exception FAILED
        ReferenceError: Can't find variable: before
            at D:/Samples/tddcss/js/test.js:16
            at D:/Samples/tddcss/js/test.js:57
            at runModule (D:/Samples/tddcss/node_modules/karma-commonjs/client/commonjs_bridge.js:40)
            at require (D:/Samples/tddcss/node_modules/karma-commonjs/client/commonjs_bridge.js:79)
            at D:/Samples/tddcss/node_modules/karma-commonjs/client/commonjs_bridge.js:141
            at D:/Samples/tddcss/node_modules/karma-commonjs/client/commonjs_bridge.js:145
Chrome 42.0.2311 (Windows 7) Testing Kendo UI test encountered a declaration exception FAILED
        ReferenceError: before is not defined
            at Suite.<anonymous> (D:/Samples/tddcss/js/kendoUItest.js:16:5)
            at window.**cjs_module**.D:/Samples/tddcss/js/kendoUItest.js (D:/Samples/tddcss/js/kendoUItest.js:8:1)
            at runModule (D:/Samples/tddcss/node_modules/karma-commonjs/client/commonjs_bridge.js:40:5)
            at require (D:/Samples/tddcss/node_modules/karma-commonjs/client/commonjs_bridge.js:79:14)
            at D:/Samples/tddcss/node_modules/karma-commonjs/client/commonjs_bridge.js:141:13
            at D:/Samples/tddcss/node_modules/karma-commonjs/client/commonjs_bridge.js:145:3
Chrome 42.0.2311 (Windows 7) My page encountered a declaration exception FAILED
        ReferenceError: before is not defined
            at Suite.<anonymous> (D:/Samples/tddcss/js/test.js:13:3)
            at window.**cjs_module**.D:/Samples/tddcss/js/test.js (D:/Samples/tddcss/js/test.js:5:1)
            at runModule (D:/Samples/tddcss/node_modules/karma-commonjs/client/commonjs_bridge.js:40:5)
            at require (D:/Samples/tddcss/node_modules/karma-commonjs/client/commonjs_bridge.js:79:14)
            at D:/Samples/tddcss/node_modules/karma-commonjs/client/commonjs_bridge.js:141:13
            at D:/Samples/tddcss/node_modules/karma-commonjs/client/commonjs_bridge.js:145:3
PhantomJS 1.9.8 (Windows 7): Executed 2 of 2 (2 FAILED) ERROR (0.008 secs / 0.002 secs)
Chrome 42.0.2311 (Windows 7): Executed 2 of 2 (2 FAILED) ERROR (0.01 secs / 0.004 secs)

Let me know.

**Comment by bjornicus** [comment]
maybe jasmine doesn't have a 'before' function? I only see "beforeEach" in the docs:
http://jasmine.github.io/2.0/introduction.html
